### ISSUE TITLE
Error watching trailers

### ISSUE THREAD

**Issue by al3azp** [popcorn-official/popcorn-android#29]
Version: Android TV  development-79
Android version:  6.0
#### Expected Behaviour

Play trailer
...
#### Actual Behaviour

crash
...
#### Steps to repoduce the behaviour

click on WATCH TRAILER

**# LOG:**

```
05-06 04:56:39.122 15427-15427/? E/QueryYouTubeTask: Error playing video!
                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
                                                         at butter.droid.base.utils.PrefUtils.getPrefs(PrefUtils.java:156)
                                                         at butter.droid.base.utils.PrefUtils.get(PrefUtils.java:125)
                                                         at butter.droid.base.vlc.VLCOptions.setMediaOptions(VLCOptions.java:137)
                                                         at butter.droid.base.fragments.BaseVideoPlayerFragment.loadMedia(BaseVideoPlayerFragment.java:299)
                                                         at butter.droid.tv.fragments.TVVideoPlayerFragment.loadMedia(TVVideoPlayerFragment.java:178)
                                                         at butter.droid.base.fragments.BaseVideoPlayerFragment.onMediaReady(BaseVideoPlayerFragment.java:266)
                                                         at butter.droid.tv.activities.TVTrailerPlayerActivity$QueryYouTubeTask.onPostExecute(TVTrailerPlayerActivity.java:180)
                                                         at butter.droid.tv.activities.TVTrailerPlayerActivity$QueryYouTubeTask.onPostExecute(TVTrailerPlayerActivity.java:112)
                                                         at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                         at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                         at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                         at android.os.Handler.dispatchMessage(Handler.java:104)
                                                         at android.os.Looper.loop(Looper.java:148)
                                                         at android.app.ActivityThread.main(ActivityThread.java:5482)
                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-06 04:56:39.135 15427-15427/? E/QueryYouTubeTask: Problem showing error dialog.
                                                     android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@246832c is not valid; is your activity running?
                                                         at android.view.ViewRootImpl.setView(ViewRootImpl.java:607)
                                                         at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
                                                         at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                         at android.app.Dialog.show(Dialog.java:319)
                                                         at butter.droid.tv.activities.TVTrailerPlayerActivity$QueryYouTubeTask.showErrorAlert(TVTrailerPlayerActivity.java:205)
                                                         at butter.droid.tv.activities.TVTrailerPlayerActivity$QueryYouTubeTask.onPostExecute(TVTrailerPlayerActivity.java:185)
                                                         at butter.droid.tv.activities.TVTrailerPlayerActivity$QueryYouTubeTask.onPostExecute(TVTrailerPlayerActivity.java:112)
                                                         at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                         at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                         at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                         at android.os.Handler.dispatchMessage(Handler.java:104)
                                                         at android.os.Looper.loop(Looper.java:148)
                                                         at android.app.ActivityThread.main(ActivityThread.java:5482)
                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-06 04:56:41.877 245-702/? E/nvaudio_hw: disable_snd_device:  snd_device ref cnt is already 0
05-06 04:56:42.320 15427-15456/? A/libc: Fatal signal 7 (SIGBUS) in tid 15456 (RenderThread)
05-06 04:56:42.428 243-243/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-06 04:56:42.428 243-243/? A/DEBUG: Build fingerprint: 'NVIDIA/foster_e/foster:6.0/MRA58K/41937_695.6426:user/release-keys'
05-06 04:56:42.428 243-243/? A/DEBUG: Revision: '0'
05-06 04:56:42.428 243-243/? A/DEBUG: ABI: 'arm64'
05-06 04:56:42.428 243-243/? A/DEBUG: pid: 15427, tid: 15456, name: RenderThread  >>> pct.droid.tv.dev <<<
05-06 04:56:42.428 243-243/? A/DEBUG: signal 7 (SIGBUS), code 0 (SI_USER), fault addr 0xa
05-06 04:56:42.445 243-243/? A/DEBUG:     x0   0000000000000002  x1   0000002033d85e08  x2   0000000000000034  x3   0000000000000033
05-06 04:56:42.445 243-243/? A/DEBUG:     x4   0000000000000000  x5   0000000000000001  x6   000000000000000a  x7   0000000000000000
05-06 04:56:42.445 243-243/? A/DEBUG:     x8   0000000000000001  x9   00000000001d3c00  x10  000000003de76d98  x11  000000204be00998
05-06 04:56:42.445 243-243/? A/DEBUG:     x12  000000204be009a0  x13  00000020306df000  x14  0000000000000000  x15  00000020306d1000
05-06 04:56:42.445 243-243/? A/DEBUG:     x16  0000002031e99dc0  x17  0000002030b1592c  x18  00000020306e2f60  x19  000000204828d820
05-06 04:56:42.445 243-243/? A/DEBUG:     x20  000000204828d820  x21  0000000000000000  x22  000000204be00998  x23  0000002033c42470
05-06 04:56:42.446 243-243/? A/DEBUG:     x24  0000000000000001  x25  0000002048373200  x26  000000204bc3cc00  x27  000000204bd37800
05-06 04:56:42.446 243-243/? A/DEBUG:     x28  00000020481d3e00  x29  000000203a16a110  x30  0000002031e20d44
05-06 04:56:42.446 243-243/? A/DEBUG:     sp   000000203a16a110  pc   0000002030b159d8  pstate 0000000020000000
05-06 04:56:42.458 243-243/? A/DEBUG:     #00 pc 00000000001959d8  /system/lib64/libskia.so (SkPaint::~SkPaint()+172)
05-06 04:56:42.458 243-243/? A/DEBUG:     #01 pc 0000000000038d40  /system/lib64/libhwui.so
05-06 04:56:42.458 243-243/? A/DEBUG:     #02 pc 0000000000038dd8  /system/lib64/libhwui.so
05-06 04:56:42.458 243-243/? A/DEBUG:     #03 pc 0000000000068604  /system/lib64/libhwui.so
05-06 04:56:42.458 243-243/? A/DEBUG:     #04 pc 0000000000068490  /system/lib64/libhwui.so
05-06 04:56:42.458 243-243/? A/DEBUG:     #05 pc 0000000000025d28  /system/lib64/libhwui.so
05-06 04:56:42.458 243-243/? A/DEBUG:     #06 pc 0000000000029108  /system/lib64/libhwui.so
05-06 04:56:42.458 243-243/? A/DEBUG:     #07 pc 0000000000028dd8  /system/lib64/libhwui.so
05-06 04:56:42.458 243-243/? A/DEBUG:     #08 pc 000000000002bb4c  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+124)
05-06 04:56:42.458 243-243/? A/DEBUG:     #09 pc 0000000000015aa8  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+208)
05-06 04:56:42.458 243-243/? A/DEBUG:     #10 pc 000000000008f290  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+96)
05-06 04:56:42.459 243-243/? A/DEBUG:     #11 pc 00000000000152f8  /system/lib64/libutils.so
05-06 04:56:42.459 243-243/? A/DEBUG:     #12 pc 0000000000065ce4  /system/lib64/libc.so (__pthread_start(void*)+52)
05-06 04:56:42.459 243-243/? A/DEBUG:     #13 pc 000000000001ebc4  /system/lib64/libc.so (__start_thread+16)
05-06 04:56:42.780 243-243/? E/DEBUG: AM write failed: Broken pipe
05-06 04:56:42.815 1197-1197/? E/ApplicationPackageManager: android not found in CATEGORY_LEANBACK_LAUNCHER
05-06 04:56:43.494 15890-15923/? E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                   Process: pct.droid.tv.dev, PID: 15890
                                                   java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling
                                                       at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2116)
                                                       at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:4027)
                                                       at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:9266)
                                                       at android.support.v7.widget.RecyclerView$Adapter.notifyItemRangeInserted(RecyclerView.java:5636)
                                                       at android.support.v17.leanback.widget.ItemBridgeAdapter$1.onItemRangeInserted(ItemBridgeAdapter.java:156)
                                                       at android.support.v17.leanback.widget.ObjectAdapter$DataObservable.notifyItemRangeInserted(ObjectAdapter.java:89)
                                                       at android.support.v17.leanback.widget.ObjectAdapter.notifyItemRangeInserted(ObjectAdapter.java:184)
                                                       at android.support.v17.leanback.widget.ArrayObjectAdapter.addAll(ArrayObjectAdapter.java:116)
                                                       at butter.droid.tv.fragments.TVMediaGridFragment$1.onSuccess_aroundBody0(TVMediaGridFragment.java:144)
                                                       at butter.droid.tv.fragments.TVMediaGridFragment$1$AjcClosure1.run(TVMediaGridFragment.java:1)
                                                       at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
                                                       at hugo.weaving.internal.Hugo.logAndExecute(Hugo.java:39)
                                                       at butter.droid.tv.fragments.TVMediaGridFragment$1.onSuccess(TVMediaGridFragment.java:138)
                                                       at butter.droid.base.providers.media.MoviesProvider$1.onResponse(MoviesProvider.java:200)
                                                       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
                                                       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                       at java.lang.Thread.run(Thread.java:818)
```

**Comment by marcuscarvalho** [comment]
@al3azp Can you try build 162 and let us know if it fixes the issue?

https://ci.popcorntime.sh/job/Popcorn-Time-Android/162/
