### ISSUE TITLE
Crash on open Nexus 6P

### ISSUE THREAD

**Issue by hiroshimanagasaki** [popcorn-official/popcorn-android#3]
I downloaded the correct version for my Android device which is a 64-bit ARMv8-A‎ but as soon as I open the app it says Popcorn Time has stopped. On stock Android 6.0.1 Marshmallow.

**Comment by TheWolfer22** [comment]
Version 0.2.8 armv7 on mi LG G3 (Marshmallow) crashes when i try to open the app. I want to remark that this doesn't happen with 0.2.7 armv7 version.

**Comment by Derevko** [comment]
Confirm it. Previous versions doesn't crash

**Comment by camilosampedro** [comment]
It crashes in my Zidoo device too (Android 4.4) it only shows the terms and then it crashes every time it is opened.

**Comment by tistaharahap** [comment]
This is the exception on my Nexus 5 running `0.2.8 - armeabi v7a`:

```02-21 03:58:34.164  9898  9898 E AndroidRuntime: FATAL EXCEPTION: main
02-21 03:58:34.164  9898  9898 E AndroidRuntime: Process: pct.droid, PID: 9898
02-21 03:58:34.164  9898  9898 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{pct.droid/pct.droid.activities.MainActivity}: java.lang.IllegalArgumentException: Can only use lower 8 bits for requestCode
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Can only use lower 8 bits for requestCode
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.validateRequestPermissionsRequestCode(FragmentActivity.java:799)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompat23.java:29)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:316)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at pct.droid.activities.MainActivity.onCreate(MainActivity.java:107)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6251)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
02-21 03:58:34.164  9898  9898 E AndroidRuntime: 	... 9 more```

**Comment by tistaharahap** [comment]
Looking at this [commit](https://github.com/popcorn-official/popcorn-android/commit/37b76b9ffc2eba372b5ad3d53f520a41ed1e9d3d), the `PERMISSIONS_REQUEST` valued used to be `1232` which is more than `255`.
