### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by tnwr0047** [popcorn-official/popcorn-android#530]
Version:  
Download date:  
Android version:  

#### Actual Behaviour

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String butter.droid.base.providers.media.response.models.common.Images.getPoster()' on a null object reference
	at butter.droid.base.providers.media.response.MovieResponse.formatListForPopcorn(MovieResponse.java:53)
	at butter.droid.base.providers.media.MoviesProvider.getResponseFormattedList(MoviesProvider.java:49)
	at butter.droid.base.providers.media.MediaProvider$1.onResponse(MediaProvider.java:195)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

#### Steps to repoduce the behaviour

1. ...open popcorntimes on Android
2. ...through movies
3. ...under titles TOP RATED, RELEASED DATE, YEAR

**Comment by MrRory** [comment]
Please provide a version in your bug reports.
