### ISSUE TITLE
App crash when it tries to look for update

### ISSUE THREAD

**Issue by SscSPs** [popcorn-official/popcorn-android#745]
## Describe the bug
The app crashes on its own when opened. was working normally just a second before

## To Reproduce
Not sure how it can be reproduced

## Expected behavior
app should not crash and open normally

### INITIAL Crash logs: 
> 03-31 00:34:47.402  1414  1522 I ActivityManager: Start proc 28628:pct.droid/u0a246 for activity {pct.droid/butter.droid.activities.MainActivity}
> 03-31 00:34:47.525  1414  3970 D OnePlusSmartBoostManager: writeHotCount pct.droid, pid=28628
> 03-31 00:34:47.525  1414  1536 E OPPerf  : Exception : file not exits :/proc/28628/main_boost_switch
> 03-31 00:34:47.550  1414  1515 D Foreground_io: TOP_APP is ProcessRecord{97355c4 28628:pct.droid/u0a246} uid is 10246
> 03-31 00:34:49.528  1414  1536 E OPPerf  : Exception : file not exits :/proc/28628/main_boost_switch
> 03-31 00:34:50.066  1414  3580 I ActivityTaskManager: START u0 {cmp=pct.droid/butter.droid.activities.SearchActivity} from uid 10246 pid 28628
> 03-31 00:35:13.165 28628 28816 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
> 03-31 00:35:13.165 28628 28816 E AndroidRuntime: Process: pct.droid, PID: 28628
> 03-31 00:35:13.165 28628 28816 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
> 03-31 00:35:13.165 28628 28816 E AndroidRuntime:        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
> 03-31 00:35:13.165 28628 28816 E AndroidRuntime:        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
> 03-31 00:35:13.165 28628 28816 E AndroidRuntime:        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
> 03-31 00:35:13.165 28628 28816 E AndroidRuntime:        at butter.droid.base.ButterApplication.updateAvailable(ButterApplication.java:141)
> 03-31 00:35:13.165 28628 28816 E AndroidRuntime:        at butter.droid.base.manager.updater.ButterUpdateManager$4.onResponse(ButterUpdateManager.java:243)
> 03-31 00:35:13.165 28628 28816 E AndroidRuntime:        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
> 03-31 00:35:13.165 28628 28816 E AndroidRuntime:        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
> 03-31 00:35:13.165 28628 28816 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 03-31 00:35:13.165 28628 28816 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 03-31 00:35:13.165 28628 28816 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)
> 03-31 00:35:13.643  1414  3970 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 28628 uid 10246
> 03-31 00:35:13.688  1414  1537 E OnePlusSmartBoostManager: Exception : file not exits :/proc/28628/memplus_type
> 03-31 00:35:13.720  1414  1433 I ActivityManager: Process pct.droid (pid 28628) has died: cch+5 SVC 
> 03-31 00:35:13.764  1414  1433 D BFP     : ProcessRecord{97355c4 28628:pct.droid/u0a246} died but not restart......
> 03-31 00:35:13.893  1414  1515 W ActivityManager: setHasOverlayUi called on unknown pid: 28628

### Subsequent crash logcat
> 03-31 00:40:15.148   732   732 D Zygote  : Forked child process 31656
> 03-31 00:40:15.150  1414  1522 I ActivityManager: Start proc 31656:pct.droid/u0a246 for activity {pct.droid/butter.droid.activities.MainActivity}
> 03-31 00:40:15.147 31656 31656 W main    : type=1400 audit(0.0:110511): avc: granted { read } for name="u:object_r:net_dns_prop:s0" dev="tmpfs" ino=16779 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:net_dns_prop:s0 tclass=file
> 03-31 00:40:15.157 31656 31656 E pct.droid: Not starting debugger since process cannot load the jdwp agent.
> 03-31 00:40:15.165  1414  1432 D OnePlusSmartBoostManager: writeHotCount pct.droid, pid=31656
> 03-31 00:40:15.165  1414  1536 E OPPerf  : Exception : file not exits :/proc/31656/main_boost_switch
> 03-31 00:40:15.172  1111 31676 E ANDR-RAMBOOST_SERVER: ramboost cmd_len = 76 cmd: iop_start 31656 pct.droid /data/app/pct.droid-5T3odKlvIlpfJWjfyesVgw== false
> 03-31 00:40:15.185  1414  1515 D Foreground_io: TOP_APP is ProcessRecord{dbf25c8 31656:pct.droid/u0a246} uid is 10246
> 03-31 00:40:15.192 31656 31656 I pct.droid: The ClassLoaderContext is a special shared library.
> 03-31 00:40:15.195 31656 31656 W pct.droid: Insufficient pre-allocated space to mmap vdex.
> 03-31 00:40:15.203 31656 31656 I Perf    : Connecting to perf service.
> 03-31 00:40:15.205 31656 31656 I pct.droid: [GL_OOM] ClampGrowthLimit 268435456
> 03-31 00:40:15.206 31656 31656 I MultiDex: VM with version 2.1.0 has multidex support
> 03-31 00:40:15.206 31656 31656 I MultiDex: install
> 03-31 00:40:15.206 31656 31656 I MultiDex: VM has multidex support, MultiDex support library is disabled.
> 03-31 00:40:15.220 31656 31656 D NetworkSecurityConfig: No Network Security Config specified, using platform default
> 03-31 00:40:15.223 31656 31656 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
> 03-31 00:40:15.229 31656 31656 W nAnnotationIntrospector: Unable to load JDK7 annotation types; will have to skip
> 03-31 00:40:15.239 31656 31656 V Font    : Change font:1
> 03-31 00:40:15.239 31656 31656 V Font    : Default family:android.graphics.Typeface@d0a0981e
> 03-31 00:40:15.243 31656 31656 D AndroidRuntime: Shutting down VM
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime: FATAL EXCEPTION: main
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime: Process: pct.droid, PID: 31656
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime: java.lang.RuntimeException: Unable to create application butter.droid.MobileButterApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6652)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at android.app.ActivityThread.access$1600(ActivityThread.java:231)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1952)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7682)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at butter.droid.base.ButterApplication.updateAvailable(ButterApplication.java:141)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at butter.droid.base.manager.updater.ButterUpdateManager.checkUpdates(ButterUpdateManager.java:300)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at butter.droid.base.ButterApplication.onCreate(ButterApplication.java:112)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at butter.droid.MobileButterApplication.onCreate(MobileButterApplication.java:38)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1197)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6647)
> 03-31 00:40:15.243 31656 31656 E AndroidRuntime:        ... 8 more
> 03-31 00:40:15.265 31656 31656 I Process : Sending signal. PID: 31656 SIG: 9
> 03-31 00:40:15.280  1414  5859 I ActivityManager: Process pct.droid (pid 31656) has died: vis+99 TOP 
> 03-31 00:40:15.280   732   732 I Zygote  : Process 31656 exited due to signal 9 (Killed)
> 03-31 00:40:15.323  1414  1524 I libprocessgroup: Successfully killed process cgroup uid 10246 pid 31656 in 43ms

## Smartphone (please complete the following information):
 - Device: OnePlus 6T
 - OS: OxygenOS 10.3.9
 - Version: 2.10

## Additional context
The crash happens when the app is left ideal for some time and happens on every app start try after that, and keeps happening till the app's data is cleared. According to the logcat, it happens when the app tries to look for update. I've not investigated the code properly to find the root cause, just looking at the logs, and looked up the error on google, and came across this: https://stackoverflow.com/questions/48828698/java-lang-nullpointerexception-attempt-to-invoke-virtual-method-android-conten The answer provided in this thread is already implemented in the app, so i'm not sure what happened.

**Comment by SscSPs** [comment]
lol wew
