### ISSUE TITLE
can't launch on Fire stick TV 

### ISSUE THREAD

**Issue by dnldsht** [popcorn-official/popcorn-android#846]
Operating System Version:
Fire Stick 2nd Gen (5.2.9.5)

Popcorn Time Version:
0.3.6

Download date:

Log cat
```
I/Sentry  (11211): Not possible to read external files directory
E/AndroidRuntime(11211): FATAL EXCEPTION: main
E/AndroidRuntime(11211): Process: pct.droid.tv, PID: 11211
E/AndroidRuntime(11211): java.lang.RuntimeException: Unable to create application butter.droid.tv.TVButterApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getParent()' on a null object reference
E/AndroidRuntime(11211):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4905)
E/AndroidRuntime(11211):        at android.app.ActivityThread.access$1600(ActivityThread.java:168)
E/AndroidRuntime(11211):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
E/AndroidRuntime(11211):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11211):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(11211):        at android.app.ActivityThread.main(ActivityThread.java:5619)
E/AndroidRuntime(11211):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11211):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(11211):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
E/AndroidRuntime(11211):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/AndroidRuntime(11211): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getParent()' on a null object reference
E/AndroidRuntime(11211):        at butter.droid.base.utils.StorageUtils.getAllStorageLocations(StorageUtils.java:60)
E/AndroidRuntime(11211):        at butter.droid.base.utils.StorageUtils.getIdealCacheDirectory(StorageUtils.java:162)
E/AndroidRuntime(11211):        at butter.droid.base.data.DataModule.provideCache(DataModule.java:53)
E/AndroidRuntime(11211):        at butter.droid.base.data.DataModule_ProvideCacheFactory.get(DataModule_ProvideCacheFactory.java:29)
E/AndroidRuntime(11211):        at butter.droid.base.data.DataModule_ProvideCacheFactory.get(DataModule_ProvideCacheFactory.java:10)
E/AndroidRuntime(11211):        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
E/AndroidRuntime(11211):        at butter.droid.base.data.DataModule_ProvideOkHttpClientFactory.get(DataModule_ProvideOkHttpClientFactory.java:35)
E/AndroidRuntime(11211):        at butter.droid.base.data.DataModule_ProvideOkHttpClientFactory.get(DataModule_ProvideOkHttpClientFactory.java:11)
E/AndroidRuntime(11211):        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
E/AndroidRuntime(11211):        at butter.droid.base.manager.updater.ButterUpdateManager_Factory.get(ButterUpdateManager_Factory.java:45)
E/AndroidRuntime(11211):        at butter.droid.base.manager.updater.ButterUpdateManager_Factory.get(ButterUpdateManager_Factory.java:12)
E/AndroidRuntime(11211):        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
E/AndroidRuntime(11211):        at butter.droid.base.ButterApplication_MembersInjector.injectUpdateManager(ButterApplication_MembersInjector.java:46)
E/AndroidRuntime(11211):        at butter.droid.tv.TVButterApplication_MembersInjector.injectMembers(TVButterApplication_MembersInjector.java:38)
E/AndroidRuntime(11211):        at butter.droid.tv.TVButterApplication_MembersInjector.injectMembers(TVButterApplication_MembersInjector.java:9)
E/AndroidRuntime(11211):        at butter.droid.tv.DaggerApplicationComponent.inject(DaggerApplicationComponent.java:314)
E/AndroidRuntime(11211):        at butter.droid.tv.TVButterApplication.onCreate(TVButterApplication.java:44)
E/AndroidRuntime(11211):        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1015)
E/AndroidRuntime(11211):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4902)
E/AndroidRuntime(11211):        ... 9 more
I/AndroidRuntime(11211): To Report FATAL to activityManagerService
I/ActivityManager( 1002): handleApplicationCrash
I/CrashReporter( 1002): CPU cores online info: 1111
W/ActivityManager( 1002):   Force finishing activity 1 pct.droid.tv/butter.droid.tv.activities.TVLaunchActivity
I/ActivityManager( 1002): addErrorToDropBox inserted hashcode=2242bc7682691295f2031f4d409ad1ef3058832d for eventType crash.
I/Vlog    ( 1002): 3p:bg_crash:fgtracking=false;DV;1,key=pct.droid.tv;DV;1,Counter=1;CT;1,unit=count;DV;1,metadata=2242bc7682691295f2031f4d409ad1ef3058832d!{"d"#{"groupId"#"u2gv3pak"$"schemaId"#"9r2z/2/01830410"$"app_version"#"30000001"}};DV;1:HI
W/InputMethodManagerService( 1002): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@2523f756 attribute=null, token = android.os.BinderProxy@958ff5c
I/Vlog    ( 1002): 3p:fg_crash:fgtracking=false;DV;1,key=pct.droid.tv;DV;1,Counter=1;CT;1,unit=count;DV;1,metadata=2242bc7682691295f2031f4d409ad1ef3058832d!{"d"#{"groupId"#"u2gv3pak"$"schemaId"#"9r2z/2/01830410"$"isChild"#"false"$"app_version"#"30000001"$"source"#"dropbox"}};DV;1:HI
I/AndroidRuntime(11211): Finished reporting FATAL to activityManagerService
I/Process (11211): Sending signal. PID: 11211 SIG: 9
I/art     ( 1002): Background sticky concurrent mark sweep GC freed 26660(1785KB) AllocSpace objects, 8(245KB) LOS objects, 5% free, 23MB/24MB, paused 14.644ms total 84.864ms
W/MediaCodecLogger-Jni( 1402): No clients currently registered
E/MediaCodecLogger-Jni( 1402): No active media clients registered
W/MediaCodecLoggerInfo( 1402): Failed to get package name
I/CrashDescriptorUtil( 1002): addErrorToCommonLog Hash already present in file
I/ActivityManager( 1002): Process pct.droid.tv (pid 11211) has died
W/Eve     ( 1002): MEMORY_LEVEL: [11211,1]
W/Eve     ( 1002):   top=pct.droid.tv/butter.droid.tv.activities.TVLaunchActivity launching=true
W/Eve     ( 1002):   prev=com.amazon.tv.settings.v2/.tv.applications.ApplicationsActivity screen_on=true thermal=0
W/Eve     ( 1002):   adb=true downloading=false
W/Eve     ( 1002):   memory=1 trim=5 available=136324KB free=80568KB
```

**Comment by kiriles90** [comment]
The firestick for some reason auto hides/denies the microphone permission that the app asks for so it cant launch.  

Even if the microphone permission isn't strictly necessary since the voice search isn't fully functioning, or even if a device doesn't have a microphone, hiding such prompts from the user is their error and would prevent many apps from launching.  

Closing this but check the existing relevant issues if you want.
Open issue at https://github.com/popcorn-official/popcorn-android/issues/804 concerning the necessity of the microphone permission and closed (since this is on their end to fix) issue at https://github.com/popcorn-official/popcorn-android/issues/800 about the firestick behavior.
