### ISSUE TITLE
App crashes on Android TV

### ISSUE THREAD

**Issue by shielduser** [popcorn-official/popcorn-android#9]
App crashes in shield android tv running on Marshmallow. I am using the latest stable build (armv8 1.2b65).

**Comment by lejeremy** [comment]
Hi,

Same problem here since marshmallow update. Before that, the androidtv app was working like a charm (very nice work !)

**Comment by atheleron** [comment]
#2

**Comment by pct-team** [comment]
We need a logcat output to see the problem. No Shield TV here.

**Comment by al3azp** [comment]
log from android studio, debugging on Shield TV marshmallow.
running PCT from Github source 10-03-2016.
- no crash after the app started.
- crash when play trailers.
- crash when trying to open certain movies or TVs like (The Good Dinosaur).

[log_10-03-2016.txt](https://github.com/popcorn-official/popcorn-android/files/167167/log_10-03-2016.txt)

**Comment by pct-team** [comment]
```
03-10 16:17:16.756 623-623/pct.droid.tv.dev E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v7.graphics.Palette$Swatch.getRgb()' on a null object reference
                                                                    at butter.droid.tv.fragments.TVOverviewFragment.onMediaItemClicked(TVOverviewFragment.java:293)
                                                                    at butter.droid.tv.fragments.TVOverviewFragment.onItemClicked(TVOverviewFragment.java:114)
                                                                    at android.support.v17.leanback.widget.ListRowPresenter$ListRowPresenterItemBridgeAdapter$1.onClick(ListRowPresenter.java:121)
                                                                    at android.view.View.performClick(View.java:5198)
                                                                    at android.view.View.onKeyUp(View.java:9879)
                                                                    at android.view.KeyEvent.dispatch(KeyEvent.java:2664)
                                                                    at android.view.View.dispatchKeyEvent(View.java:9234)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1635)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                    at android.support.v17.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:764)
                                                                    at android.support.v17.leanback.widget.HorizontalGridView.dispatchKeyEvent(HorizontalGridView.java:50)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                    at android.support.v17.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:764)
                                                                    at android.support.v17.leanback.widget.VerticalGridView.dispatchKeyEvent(VerticalGridView.java:40)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                    at com.android.internal.policy.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2395)
                                                                    at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1727)
                                                                    at android.app.Activity.dispatchKeyEvent(Activity.java:2725)
                                                                    at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4273)
                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4235)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3783)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3836)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3802)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3931)
                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3810)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3988)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3783)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3836)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3802)
                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3810)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3783)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3836)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3802)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3964)
                                                                    at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4125)
                                                                    at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2264)
                                                                    at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1885)
                                                                    at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1876)
                                                                    at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2241)
                                                                	at android.view.InputEventSender.dispatchInputEventFinished
03-10 16:17:16.759 623-623/pct.droid.tv.dev D/AndroidRuntime: Shutting down VM
03-10 16:17:16.760 623-623/pct.droid.tv.dev E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: pct.droid.tv.dev, PID: 623
                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v7.graphics.Palette$Swatch.getRgb()' on a null object reference
                                                                  at butter.droid.tv.fragments.TVOverviewFragment.onMediaItemClicked(TVOverviewFragment.java:293)
                                                                  at butter.droid.tv.fragments.TVOverviewFragment.onItemClicked(TVOverviewFragment.java:114)
                                                                  at android.support.v17.leanback.widget.ListRowPresenter$ListRowPresenterItemBridgeAdapter$1.onClick(ListRowPresenter.java:121)
                                                                  at android.view.View.performClick(View.java:5198)
                                                                  at android.view.View.onKeyUp(View.java:9879)
                                                                  at android.view.KeyEvent.dispatch(KeyEvent.java:2664)
                                                                  at android.view.View.dispatchKeyEvent(View.java:9234)
                                                                  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1635)
                                                                  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                  at android.support.v17.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:764)
                                                                  at android.support.v17.leanback.widget.HorizontalGridView.dispatchKeyEvent(HorizontalGridView.java:50)
                                                                  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                  at android.support.v17.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:764)
                                                                  at android.support.v17.leanback.widget.VerticalGridView.dispatchKeyEvent(VerticalGridView.java:40)
                                                                  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                  at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                  at com.android.internal.policy.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2395)
                                                                  at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1727)
                                                                  at android.app.Activity.dispatchKeyEvent(Activity.java:2725)
                                                                  at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4273)
                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4235)
                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3783)
                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3836)
                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3802)
                                                                  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3931)
                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3810)
                                                                  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3988)
                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3783)
                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3836)
                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3802)
                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3810)
                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3783)
                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3836)
                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3802)
                                                                  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3964)
                                                                  at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4125)
                                                                  at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2264)
                                                                  at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1885)
                                                                  at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1876)
                                                                  at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2241)
                                                              	at 
```

**Comment by pct-team** [comment]
this doesnt look to be something with pt specifically

**Comment by lejeremy** [comment]
Maybe checking if it is null before calling getrgb method could help ?

**Comment by lejeremy** [comment]
Now working with 0.1.3. Thanks !

**Comment by lejeremy** [comment]
Edit: there is still random crashes but the app is now usable
